language: node_js
node_js:
- '10'

before_install:
- npm install -g @angular/cli
install: npm install

branches:
  only:
  - master


deploy:
  skip_cleanup: true
  provider: heroku
  app: task-tracker20
  api_key: 